Run warmup with chosen strategy in benchmark_single_circuit (#35)
# What ❔

In current code, each `benchmark_single_circuit` iteration does a warmup
run _before_ choosing the strategy that fits the iteration's memory
limit. This caused a genuine
```thread 'test::zksync::benchmark_single_circuit' panicked at 'gpu proof: ErrorMemoryAllocation', src/test.rs:1221:14```
panic (from a warmup run) when I ran it.

## Why ❔

With this diff, `benchmark_single_circuit` runs end to end without panics.

I reread when and how the setup cache is created, as well as `_setup_cache_reset()`'s other points of use, to decide when the test should call `_setup_cache_reset()`. But I'm obviously not as familiar as you, so please double check that I'm calling it in the right places :P

## Checklist

- [ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zk fmt` and `zk lint`.